### ISSUE TITLE
pyproject.toml vs separate config files

### ISSUE THREAD

**Issue by proxi** [Doist/cookiecutter-python-project#4]
@Doist/integrations @Doist/back-end Was the decision to put config into separate files (e.g. isort.cfg) intentional? We can also put it (for most tools) in pyproject.toml. Let's discuss pros and cons and decide what should be baseline.

Pros on keeping separate files:
- separate file is easier to copy vs copying a section in .toml file

Cons:
- more files in root directory
- tooling history harder to track across multiple files

**Comment by jankratochvilcz** [comment]
@imankulov might be the only one with the necessary context here :-)

**Comment by proxi** [comment]
@jankratochvilcz Maybe to answer "why it was this way?", but to answer "how it should be?", I think both of Backend and Integrations should participate. In fact Integrations repos are better role models until backend gets cleaned up.

**Comment by caiocarrara** [comment]
@proxi @jankratochvilcz I don't have all Doist context, but I think I can help to understand the `pyproject.toml` situation here. The thing is that `pyproject.yaml` is relatively new on Python ecosystem. The PEP (Python enhancement proposal) that created this specification was [created and approved in 2016](https://www.python.org/dev/peps/pep-0518/). After that it took some time to tools start to implement the support for it. So, maybe this is the reason we don't fully use it yet.

**Comment by amleczko** [comment]
I don't have any strong opinions. However, it would be beneficial for me (and maybe other python developers) if we have one convention and all doist python projects follows that convention.

**Comment by lefcha** [comment]
Yes, both approaches have good and bad... I think I prefer separate configs, as I am worried that we may need to rely on pyproject support for each tool...

**Comment by proxi** [comment]
>  I am worried that we may need to rely on pyproject support for each tool

Is there some "support" needed other that just using recent enough version?

**Comment by lefcha** [comment]
I mean imagine that something changes on one of the tools, and we can't adapt because we're on pyproject's global config, it's less flexible to rely on another wrapper tool.  Unless the config is passed as is to the tools, and nothing like this can happen.

**Comment by jankratochvilcz** [comment]
@proxi I wonder if this is something we discussed analogously for package.json as well and we could apply the conclusions here?

Btw. @lefcha @proxi I recommend that you make a recommendation and wait if someone disagrees, it'll be faster than trying to converge to a solution as a group.

**Comment by caiocarrara** [comment]
@proxi @lefcha @jankratochvilcz 

> I am worried that we may need to rely on pyproject support for each tool

It's important to mention that `pyproject.yaml` is a Python standard. The specification is based in a PEP ([ref](https://www.python.org/dev/peps/pep-0518/)) and it means a lot to Python ecosystem. All major tools, specially the ones we use, already has support for settings defined on `pyproject.toml`. [Black](https://black.readthedocs.io/en/stable/pyproject_toml.html), [isort](https://pycqa.github.io/isort/docs/configuration/options/#example-pyprojecttoml) and [pytest](https://docs.pytest.org/en/stable/customize.html#pyproject-toml) for example. As it is a Python standard and it has a serious weight for the entire community, I would say it's relatively safe to rely on long-term support for it.

So, I allow myself to say that relying on `pyproject.toml` config file is better because we're relying on a fundamental standard and not in an "ad-hoc" solution done by each tool/project.

> and we can't adapt because we're on pyproject's global config

I'm not sure about it. Anyway, we can follow some principles:

1. We define our Python tool configurations on `pyproject.toml` because this is the standard;
2. The tools we use need to be updated to support the principle 1
3. Valuing more pragmatism than purism, we should keep ourselves open to a few exceptions.

**Comment by lefcha** [comment]
If it's a Python/PEP standard, and we can rely on it, and all tools we use support it well, then I'm inclining to using the global `pyproject.yaml`.

**Comment by PotHix** [comment]
+1 for using only the `pyproject.yaml`

**Comment by proxi** [comment]
We aren't really using this template much, closing as not actionable.
